name: CI to Docker Hub

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Load Cache Keys
        uses: actions/cache@v1
        id: cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Load cached Docker layers
        run: |
          if [ -d "docker-cache" ]; then
            cat docker-cache/x* > pawel-falcon.tar
            docker load < pawel-falcon.tar
            rm -rf docker-cache
            rm -rf pawel-falcon.tar
          fi
      
      - name: Build image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker-compose build pawel-falcon
          docker save pawel-falcon $(docker history -q pawel-falcon | awk '!/<missing>/{print}') > pawel-falcon.tar
          mkdir docker-cache
          split -b 100m pawel-falcon.tar docker-cache/x
          rm -rf pawel-falcon.tar
      
      - name: Check docker info
        run: docker info

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          tag-name: pawel-falcon
          image-version: ver1.0
        with:
          image-ref: '${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.tag-name }}:${{ env.image-version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
