name: CI to Docker Hub

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-dock
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: /var/lib/docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Build dockerimage
        run: docker-compose build
      
      - name: Check docker info
        run: docker info

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          tag-name: pawel-falcon
          image-version: ver1.0
        with:
          image-ref: '${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.tag-name }}:${{ env.image-version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
