name: CI to Docker Hub

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build docker-compose stack
        id: docker_build
        run: docker-compose -f docker-compose.yml up -d --build
      
      - name: Check folder
        run: pwd
      
      - name: Check files
        run: ls -ltr

      - name: Check running containers
        run: docker ps
        