name: CI to Docker Hub

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-docker
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: /var/lib/docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build dockerimage
        run: docker-compose build

      - name: Check running containers
        run: docker ps
