name: CI to Docker Hub

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      tag-name: pawel-falcon
      version: ver1.0
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Load Cache Keys
        uses: actions/cache@v1
        id: cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Load cached Docker layers
        run: |
          if [ -d "docker-cache" ]; then
            cat docker-cache/x* > ${{ env.tag-name }}.tar
            docker load < ${{ env.tag-name }}.tar
            rm -rf docker-cache
            rm -rf ${{ env.tag-name }}.tar
          fi
      
      - name: Build image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker-compose build ${{ env.tag-name }}
          docker save ${{ env.tag-name }}:${{ env.version }} $(docker history -q ${{ env.tag-name }}:${{ env.version }} | awk '!/<missing>/{print}') > ${{ env.tag-name }}.tar
          mkdir docker-cache
          split -b 100m ${{ env.tag-name }}.tar docker-cache/x
          rm -rf ${{ env.tag-name }}.tar
      
      - name: Check docker info
        run: docker info

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.tag-name }}:${{ env.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
